### ISSUE TITLE
Fairseq安装依赖问题

### ISSUE THREAD

**Issue by xy1137030414** [blcuicall/mcts#2]
1.虚拟机：PyTorch  2.1.0 Python  3.10(ubuntu22.04) Cuda  12.1
2.新建了python虚拟环境，并指定python版本为3.11.10.
3.之后按照mcts文档下载相应版本的包
4.安装fairseq：git clone→ cd fairseq→ 按照文档下载特定版本的fairseq→pip install 特定的版本
5.显示安装成功，但有报错和警告：
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: fairseq
  Attempting uninstall: fairseq
    Found existing installation: fairseq 1.0.0a0+06c65c8
    Uninstalling fairseq-1.0.0a0+06c65c8:
      Successfully uninstalled fairseq-1.0.0a0+06c65c8
Successfully installed fairseq-1.0.0a0+06c65c8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: There was an error checking the latest version of pip.
6.利用python -c "import fairseq; print(fairseq.__version__)"查询是否安装成功，报错如下：
(forst) root@autodl-container-98e944be4b-90b41232:~/fairseq# python -c "import fairseq; print(fairseq.__version__)"
common - <dataclasses._MISSING_TYPE object at 0x7fb1f649c290>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/fairseq/fairseq/__init__.py", line 31, in <module>
    hydra_init()
  File "/root/fairseq/fairseq/dataclass/initialize.py", line 25, in hydra_init
    cs.store(name=k, node=v)
  File "/root/miniconda3/envs/forst/lib/python3.11/site-packages/hydra/core/config_store.py", line 85, in store
    cfg = OmegaConf.structured(node)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/forst/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 140, in structured
    return OmegaConf.create(obj, parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/forst/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 177, in create
    return OmegaConf._create_impl(obj=obj, parent=parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/forst/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 245, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/root/miniconda3/envs/forst/lib/python3.11/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/root/miniconda3/envs/forst/lib/python3.11/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
    ^^^^^^^^
omegaconf.errors.ValidationError: Object of unsupported type: '_MISSING_TYPE'
        full_key: 
        reference_type=None
        object_type=None
 7.显示错误如上，我对下载好的特定版本的fairseq的config配置文件进行了修改：
 @dataclass
class FairseqConfig(FairseqDataclass):
    common: CommonConfig = field(default_factory=CommonConfig)
    common_eval: CommonEvalConfig = field(default_factory=CommonEvalConfig)
    distributed_training: DistributedTrainingConfig = field(default_factory=DistributedTrainingConfig)
    dataset: DatasetConfig = field(default_factory=DatasetConfig)
    optimization: OptimizationConfig = field(default_factory=OptimizationConfig)
    checkpoint: CheckpointConfig = field(default_factory=CheckpointConfig)
    bmuf: FairseqBMUFConfig = field(default_factory=FairseqBMUFConfig)
    generation: GenerationConfig = field(default_factory=GenerationConfig)
    eval_lm: EvalLMConfig = field(default_factory=EvalLMConfig)
    interactive: InteractiveConfig = field(default_factory=InteractiveConfig)
    model: Any = field(default_factory=lambda: "default_model")  # 提供默认值或工厂函数
    task: Optional[Any] = None  # 标记为可选字段
    criterion: Optional[Any] = None
    optimizer: Optional[Any] = None
    lr_scheduler: Optional[Any] = None
    scoring: Optional[Any] = None
    bpe: Optional[Any] = None
    tokenizer: Optional[Any] = None
    ema: EMAConfig = field(default_factory=EMAConfig)
    8.然后还是不行。事实上在pip命令提示安装成功后，我就利用bash /root/mcts/scripts/simplification/data_process.sh命令尝试运行bpe.py和预处理文件，bpe文件可以正常运行输出，然后process文件就一开始缺少必要的依赖项，我按照提示下载了依赖项：omegaconf==2.0.6 和 hydra-core==1.0.7。之后，我又重新安装了fairseq，重新sh命令，这时候开始显示各种fairseq的依赖问题（命令行输出我已经找不到了，忘记记录了），我在chatgpt的指引下修改了config文件。但是一直还是不行，我刚才贴出的报错代码是在我修改了一番后的最新报错。
    9.我的pip list：
(forst) root@autodl-container-98e944be4b-90b41232:~/fairseq# pip list
DEPRECATION: Loading egg at /root/miniconda3/envs/forst/lib/python3.11/site-packages/apex-0.1-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Package                  Version         Editable project location
------------------------ --------------- -------------------------
antlr4-python3-runtime   4.8
apex                     0.1
apex                     0.1
autocommand              2.2.2
backports.tarfile        1.2.0
bitarray                 2.9.2
certifi                  2024.8.30
cffi                     1.17.1
charset-normalizer       3.3.2
colorama                 0.4.6
Cython                   3.0.11
fairseq                  1.0.0a0+06c65c8 /root/fairseq
filelock                 3.16.1
fsspec                   2024.9.0
huggingface-hub          0.25.1
hydra-core               1.0.7
idna                     3.10
importlib_metadata       8.0.0
importlib_resources      6.4.0
inflect                  7.3.1
jaraco.collections       5.1.0
jaraco.context           5.3.0
jaraco.functools         4.0.1
jaraco.text              3.12.1
Jinja2                   3.1.4
lxml                     5.3.0
MarkupSafe               2.1.5
more-itertools           10.3.0
mpmath                   1.3.0
networkx                 3.3
numpy                    2.1.1
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.77
nvidia-nvtx-cu12         12.1.105
omegaconf                2.0.6
packaging                24.1
pip                      23.2.1
platformdirs             4.2.2
portalocker              2.10.1
pycparser                2.22
PyYAML                   6.0.2
regex                    2024.9.11
requests                 2.32.3
sacrebleu                2.4.3
safetensors              0.4.5
setuptools               75.1.0
sympy                    1.13.3
tabulate                 0.9.0
tokenizers               0.20.0
tomli                    2.0.1
torch                    2.4.1
torchaudio               2.4.1
tqdm                     4.66.5
transformers             4.45.1
triton                   3.0.0
typeguard                4.3.0
typing_extensions        4.12.2
urllib3                  2.2.3
wheel                    0.44.0
zipp                     3.19.2
10.我在怀疑是不是pip、python的版本太高导致，但是我觉得我实在是处理不了了，我可能写得不专业，因为我完全是小白，如有问题，请联系我。

**Comment by TreemanCHou** [comment]
在实验中，我们采用 `python==3.9.18` 、`CUDA 10.2` 和 `torch==2.2.1`，你可以尝试对齐到这些版本。如果有其它问题请再告诉我 : )

**Comment by xy1137030414** [comment]
> 在实验中，我们采用 `python==3.9.18` 、`CUDA 10.2` 和 `torch==2.2.1`，你可以尝试对齐到这些版本。如果有其它问题请再告诉我 : )

感谢您的解答，由于CUDA向下兼容，因此我安装了python==3.9.18，torch==2.2.1，cuda=11.8，并重新安装了wheel。之后，再次进行fairseq安装，第一次仍旧失败，命令行输出显示pip版本过高，在我使用pip==23之后成功下载了fairseq包。

新问题：在数据集划分时，要求提供bart-base-chinsese的词表，其中词表应该有两列，一列为词，一列为词频（或其他），但我从抱抱脸🤗上下载的模型的词表只有词，请问课题组方便提供一份词表吗？

**Comment by TreemanCHou** [comment]
如果您是指 `dict.txt` ，可以参阅文件 [scripts](https://github.com/blcuicall/mcts/tree/main/scripts)/[simplification](https://github.com/blcuicall/mcts/tree/main/scripts/simplification)
/extract_dict.py ，使用该代码可以提取出该所需词表文件。似乎是我在 README.md 里忘记写明了，我将会补充这一点 😅😅

如果有更多问题，请继续联系🙂

**Comment by xy1137030414** [comment]
> 如果您是指 `dict.txt` ，可以参阅文件 [scripts](https://github.com/blcuicall/mcts/tree/main/scripts)/[simplification](https://github.com/blcuicall/mcts/tree/main/scripts/simplification)
> 
> /extract_dict.py ，使用该代码可以提取出该所需词表文件。似乎是我在 README.md 里忘记写明了，我将会补充这一点 😅😅
> 
> 
> 
> 如果有更多问题，请继续联系🙂

啊，好的，那我试试，谢谢☺️

**Comment by xy1137030414** [comment]
> > 如果您是指 `dict.txt` ，可以参阅文件 [scripts](https://github.com/blcuicall/mcts/tree/main/scripts)/[simplification](https://github.com/blcuicall/mcts/tree/main/scripts/simplification)
> > 
> > /extract_dict.py ，使用该代码可以提取出该所需词表文件。似乎是我在 README.md 里忘记写明了，我将会补充这一点 😅😅
> > 
> > 
> > 
> > 如果有更多问题，请继续联系🙂
> 
> 啊，好的，那我试试，谢谢☺️

您好，我想问一下这个vocab.txt是不是我下载bart后就应该生成，之后再调用bpe.py才可以正确处理训练语料。我检查了我只是用bart模型下载时提供的原始vocab.txt，然后我用bpe.py转换数据的输入基本都是[UNK]🤪🤪🤪

**Comment by xy1137030414** [comment]
![image](https://github.com/user-attachments/assets/d950e4ca-2d02-4ef8-94ee-5b45babd2366)
上述test.src是我基于bart原始的vocab.txt文件生成的。
此外，当我利用extract_dict.py生成新的vocab.txt文件时，我检查了我的输出文件，其中出现这样的问题：
![image](https://github.com/user-attachments/assets/09c9b494-de31-4b4d-ba00-120fb35c03bc)
具体问题为：词汇表中的词汇在后面，而序号在前面，这是错误的吗？我需要修改吗？

**Comment by xy1137030414** [comment]
另外，我需要对词表进行扩充吗？词表里面没有词汇，只有单个汉字，这可能是导致test.src文件中全部都是ukn

**Comment by xy1137030414** [comment]
> 如果您是指 `dict.txt` ，可以参阅文件 [scripts](https://github.com/blcuicall/mcts/tree/main/scripts)/[simplification](https://github.com/blcuicall/mcts/tree/main/scripts/simplification) /extract_dict.py ，使用该代码可以提取出该所需词表文件。似乎是我在 README.md 里忘记写明了，我将会补充这一点 😅😅
> 
> 如果有更多问题，请继续联系🙂

我已经利用extract_dict.py文件进行了voacb.txt生成，但是我对词汇表还有几个问题没搞清楚：
1.词汇表中没有词汇、只有单独的汉字。所以，当我利用bpe.py对数据进行分词和转换时，就会出现全部是[UNK] 的情况，如下图：
![image](https://github.com/user-attachments/assets/d950e4ca-2d02-4ef8-94ee-5b45babd2366)
针对这个问题，我需要自行扩充词汇表吗？

2.词汇表生成存在一些问题，见下图：
![image](https://github.com/user-attachments/assets/09c9b494-de31-4b4d-ba00-120fb35c03bc)
具体问题为：词汇表中部分字符的索引在前面，字符在后面，我不知道为什么会出现这种情况。

3.在我把训练数据分词的时候，这个时候需要加载模型路径，这个时候是不是还只能使用原始的vocab.txt。而当我训练时就需要一个带有索引列的vocab.txt吗？

以上就是我不清楚的地方，感谢您的解答！🥹🥹🥹

**Comment by TreemanCHou** [comment]
`dict.txt` 和 `vocab.txt` 是两份不同的文件，尽管其内容是相似的。因为 `preprocess.py` 代码引用的原因，我们需要从模型中提取 `dict.txt`. 详情可以参阅代码。而 `vocab.txt` 是模型官方仓库中提供的，在 huggingface 中有提供。

我没有遇到过生成词汇表中颠倒的情况。你是否可以稳定地复现这个错误并提供更多信息？假如是使用这种有问题的词汇表进行bpe等步骤，可能导致你提及的大规模 UNK 的情况。

以及，您可以检查是否正确地使用了本仓库指定的模型或是否在使用自定义数据。 ：）

**Comment by xy1137030414** [comment]
> `dict.txt` 和 `vocab.txt` 是两份不同的文件，尽管其内容是相似的。因为 `preprocess.py` 代码引用的原因，我们需要从模型中提取 `dict.txt`. 详情可以参阅代码。而 `vocab.txt` 是模型官方仓库中提供的，在 huggingface 中有提供。
> 
> 
> 
> 我没有遇到过生成词汇表中颠倒的情况。你是否可以稳定地复现这个错误并提供更多信息？假如是使用这种有问题的词汇表进行bpe等步骤，可能导致你提及的大规模 UNK 的情况。
> 
> 
> 
> 以及，您可以检查是否正确地使用了本仓库指定的模型或是否在使用自定义数据。 ：）

感谢您的回复，关于词表的问题，经过认真的阅读代码文件，我已经解决了这个问题。

关于词汇表颠倒的情况，我是直接用仓库中的测试集先转为.src，会对其进行bpe的，但我还没有多次验证这种错误是否是反复出现的。

经过我的排查，之所以出现大规模的unk是因为当时预训练模型的加载可能存在问题，后来没有出现这样的情况了。

我应该是正确使用了仓库中自定义的模型和模块，因为我的脚本运行过程中没有报错和相关警告出现。

我是使用的是仓库提供的数据集。
